// Copyright 2026 V-Sekai contributors.
// SPDX-License-Identifier: Apache-2.0 OR MPL-2.0
//
// idtx_core_export_avatar_to_scn — Godot 4 .scn (binary PackedScene)
// writer. See idtx_core.h for the public C ABI contract.
//
// Format spec: E:\lean-predictive-bvh\PredictiveBVH\Codegen\
//              GodotBinary.lean (Lean 4 model of FORMAT_VERSION=6,
//              33 variant tags, RSRC/RSCC headers, string table,
//              ext/int resource tables; strings have NO 4-byte
//              padding, validated against Godot 4.7 output).
//
// Slang emitter: openusd-fabric/lean/Fabric/Serialization/GodotScn.lean
//                emits godot_scn.slang with the variant writers +
//                headers. scons/godot_scn_writers.py lowers that to
//                C++ via `slangc -target cpp` at configure time and
//                compiles the result into libidtx_core.
//
// Test fixtures: openusd-fabric/tests/scn_validate/ — real Godot-
//                baked .scn files (simple, mesh+basisu, all-Node3D-
//                types) plus parse_scn.py and validate_all_node3d.py.
//
// When the slangc-emitted writers ARE linked (most builds),
// IDTX_GODOT_SCN_AVAILABLE is defined and the implementation delegates
// to them. When the build was configured without lake/slangc on PATH,
// the entrypoints fall back to returning 99 (not yet implemented) so
// hosts can still load libidtx_core without breaking.

#include "idtx_core/idtx_core.h"
#include "idtx_core/internal/usd_helpers.h"

#include <cstring>

#if defined(IDTX_GODOT_SCN_AVAILABLE)
// Generated by `slangc -target cpp` from openusd-fabric/lean/shaders/
// godot_scn.slang. Declares the variant writers (godot_store_u32,
// godot_store_u64, godot_write_*, godot_write_header, ...).
#  include "godot_scn.h"
#endif

extern "C" IDTX_CORE_API void idtx_scn_opts_init(idtx_scn_opts_t* opts)
{
    if (opts == nullptr) return;
    opts->compression       = IDTX_SCN_ZSTD;
    opts->block_size        = 4096;     // Godot 4 RSCC default
    opts->generate_lods     = 1;        // meshoptimizer on by default
    opts->lod_target_error  = 1.0f;     // ImporterMesh::generate_lods stop
    opts->basis_universal   = 1;        // PortableCompressedTexture2D
}

extern "C" IDTX_CORE_API int32_t idtx_core_export_avatar_to_scn(
    const idtx_avatar_t* avatar,
    const char*          path,
    const idtx_scn_opts_t* opts)
{
    if (avatar == nullptr || path == nullptr) {
        return 1;  // invalid argument
    }
#if defined(IDTX_GODOT_SCN_AVAILABLE)
    // The slangc-emitted writers operate on a uint32-indexed RW buffer
    // (per the Slang IR). idtx_godot_scn_serialize is the thin C++
    // wrapper hand-written next to the emitter; it walks the avatar,
    // calls godot_write_header → ... → godot_write_footer, then either
    // writes the buffer directly or zstd-wraps it as RSCC.
    idtx_scn_opts_t effective;
    if (opts != nullptr) {
        effective = *opts;
    } else {
        idtx_scn_opts_init(&effective);
    }
    return idtx_godot_scn_serialize(avatar, path, &effective);
#else
    (void)opts;
    return 99;  // pipeline not configured for this build
#endif
}

extern "C" IDTX_CORE_API int64_t idtx_core_export_avatar_to_scn_buffer(
    const idtx_avatar_t* avatar,
    uint8_t*             out_buf,
    size_t               out_cap,
    const idtx_scn_opts_t* opts)
{
    if (avatar == nullptr) return -1;
#if defined(IDTX_GODOT_SCN_AVAILABLE)
    idtx_scn_opts_t effective;
    if (opts != nullptr) {
        effective = *opts;
    } else {
        idtx_scn_opts_init(&effective);
    }
    return idtx_godot_scn_serialize_to_buffer(avatar, out_buf, out_cap, &effective);
#else
    (void)opts;
    if (out_buf == nullptr || out_cap == 0) {
        return -99;  // size-query path
    }
    return -99;  // pipeline not configured
#endif
}

// ---------------------------------------------------------------------
// Progress callback registry — shared state for the whole library.
// Hosts call idtx_core_set_progress_cb() once; internal call sites do:
//   if (g_progress_cb) g_progress_cb(fraction, message, g_progress_user);
// ---------------------------------------------------------------------

namespace {
idtx_progress_fn g_progress_cb   = nullptr;
void*            g_progress_user = nullptr;
}

extern "C" IDTX_CORE_API void idtx_core_set_progress_cb(
    idtx_progress_fn cb, void* user)
{
    g_progress_cb   = cb;
    g_progress_user = user;
}

// ---------------------------------------------------------------------
// idtx_core_init — one-time setup. Registers the shipped USD plugins (the
// IdtxHostUriResolver and the codeless v_sekai:* schema) with the process
// PlugRegistry so applied API schemas and the res:/user: resolver resolve
// in every host before any UsdStage::Open() call.
//
// The plugin directories are resolved RELATIVE TO THE LOADED libidtx_core
// MODULE at runtime (see register_usd_plugins), never an absolute build-time
// path, so the library stays relocatable across hosts and machines. The
// optional `plugin_dir` lets a caller name the directory explicitly.
// Returns 0 on success.
// ---------------------------------------------------------------------

extern "C" IDTX_CORE_API int32_t idtx_core_init(const char* plugin_dir)
{
    idtx::core::register_usd_plugins(plugin_dir);
    return 0;
}
