"""
Regenerate tests/fixtures/macbeth_colorchecker.usda from the 24-patch
reference values. Saves a lot of hand-editing when the Material schema
shifts (e.g. adding MaterialX alongside UsdPreviewSurface).

Copyright 2026 V-Sekai contributors.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from pathlib import Path


# (name, linear_R, linear_G, linear_B). Values are the sRGB-encoded
# floats from Wikipedia's "Manufacturer's sRGB color values" table.
PATCHES = [
    ("dark_skin",    0.451, 0.322, 0.267),
    ("light_skin",   0.761, 0.588, 0.510),
    ("blue_sky",     0.384, 0.478, 0.616),
    ("foliage",      0.341, 0.424, 0.263),
    ("blue_flower",  0.522, 0.502, 0.694),
    ("bluish_green", 0.404, 0.741, 0.667),
    ("orange",          0.839, 0.494, 0.173),
    ("purplish_blue",   0.314, 0.357, 0.651),
    ("moderate_red",    0.757, 0.353, 0.388),
    ("purple",          0.369, 0.235, 0.424),
    ("yellow_green",    0.616, 0.737, 0.251),
    ("orange_yellow",   0.878, 0.635, 0.180),
    ("blue",    0.220, 0.239, 0.588),
    ("green",   0.275, 0.580, 0.286),
    ("red",     0.686, 0.212, 0.235),
    ("yellow",  0.906, 0.780, 0.122),
    ("magenta", 0.733, 0.337, 0.584),
    ("cyan",    0.031, 0.522, 0.631),
    ("white_9_5",   0.953, 0.953, 0.953),
    ("neutral_8",   0.784, 0.784, 0.784),
    ("neutral_6_5", 0.627, 0.627, 0.627),
    ("neutral_5",   0.478, 0.478, 0.478),
    ("neutral_3_5", 0.333, 0.333, 0.333),
    ("black_2",     0.204, 0.204, 0.204),
]

# 4 rows x 6 columns. Row 0 = top (skin tones), Row 3 = bottom (neutrals).
# Patch centre positions in the (x, y) plane, world-space metres.
COLS, ROWS = 6, 4
SPACING_X = 0.20
SPACING_Y = 0.20
PATCH_SIZE = 0.18


def _xy_for_index(i: int) -> tuple[float, float]:
    col = i % COLS
    row = i // COLS
    # Centred around origin: cols go -2.5..+2.5 columns from centre.
    x = (col - (COLS - 1) / 2.0) * SPACING_X
    y = -(row - (ROWS - 1) / 2.0) * SPACING_Y
    return x, y


HEADER = '''#usda 1.0
(
    """
    X-Rite / Macbeth ColorChecker reference fixture (24 patches, 4 rows
    by 6 columns). sRGB-D65 values from Wikipedia "ColorChecker"
    (Manufacturer's sRGB color values).

    Each patch carries three forms of colour so every consumer picks
    one up:
      * `primvars:displayColor` — vertex-colour fallback for Solid
        viewport shading and renderers that bypass material bindings.
      * `outputs:surface` -> UsdPreviewSurface — hdStorm's native path.
      * `outputs:mtlx:surface` -> MaterialX `ND_standard_surface_surfaceshader`
        — Blender 4.4+ MaterialX importer, hdMtlx renderer delegates.

    Regenerated by `python scripts/generate_macbeth_fixture.py`. Do
    not hand-edit — colour values and per-Material boilerplate live in
    that script.

    Copyright 2026 V-Sekai contributors.
    SPDX-License-Identifier: MIT
    """
    defaultPrim = "Chart"
    upAxis = "Y"
    metersPerUnit = 1.0
)

def Xform "Chart"
{
'''

FOOTER = '''
    def DomeLight "Ambient"
    {
        color3f inputs:color = (1.0, 1.0, 1.0)
        float inputs:intensity = 1500
    }
}
'''


def _cube_block(idx: int, name: str, r: float, g: float, b: float) -> str:
    x, y = _xy_for_index(idx)
    return f'''    def Cube "P{idx:02d}_{name}" (prepend apiSchemas = ["MaterialBindingAPI"])
    {{
        double size = {PATCH_SIZE}
        matrix4d xformOp:transform = ( (1,0,0,0), (0,1,0,0), (0,0,1,0), ({x: .2f}, {y: .2f}, 0, 1) )
        uniform token[] xformOpOrder = ["xformOp:transform"]
        color3f[] primvars:displayColor = [({r}, {g}, {b})]
        rel material:binding = </Chart/Mats/M_{name}>
    }}
'''


def _material_block(name: str, r: float, g: float, b: float) -> str:
    return f'''        def Material "M_{name}"
        {{
            token outputs:surface.connect = </Chart/Mats/M_{name}/PreviewSurface.outputs:surface>
            token outputs:mtlx:surface.connect = </Chart/Mats/M_{name}/MtlxSurface.outputs:out>

            def Shader "PreviewSurface"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = ({r}, {g}, {b})
                token outputs:surface
            }}
            def Shader "MtlxSurface"
            {{
                uniform token info:id = "ND_standard_surface_surfaceshader"
                color3f inputs:base_color = ({r}, {g}, {b})
                float inputs:base = 1.0
                token outputs:out
            }}
        }}
'''


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "macbeth_colorchecker.usda"
    parts: list[str] = [HEADER]
    for i, (name, r, g, b) in enumerate(PATCHES):
        parts.append(_cube_block(i, name, r, g, b))
    parts.append('\n    def Scope "Mats"\n    {\n')
    for name, r, g, b in PATCHES:
        parts.append(_material_block(name, r, g, b))
    parts.append("    }\n")
    parts.append(FOOTER)
    out.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {out}  ({len(PATCHES)} patches, {sum(1 for _ in parts)} chunks)")


if __name__ == "__main__":
    main()
