package com.weftspun.xrfacebridge

/**
 * ARCore / Jetpack XR blend-shape names → WebXR expression keys (Weftspun3DStudio).
 */
object FaceBlendShapeMaps {

    val BLEND_TO_WEB: Map<String, String> = buildMap {
        fun p(short: String, web: String) {
            put(short, web)
            put("FACE_BLEND_SHAPE_TYPE_$short", web)
        }
        p("BROW_LOWERER_LEFT", "brow_lowerer_left")
        p("BROW_LOWERER_RIGHT", "brow_lowerer_right")
        p("CHEEK_PUFF_LEFT", "cheek_puff_left")
        p("CHEEK_PUFF_RIGHT", "cheek_puff_right")
        p("CHEEK_RAISER_LEFT", "cheek_raiser_left")
        p("CHEEK_RAISER_RIGHT", "cheek_raiser_right")
        p("CHEEK_SUCK_LEFT", "cheek_suck_left")
        p("CHEEK_SUCK_RIGHT", "cheek_suck_right")
        p("CHIN_RAISER_BOTTOM", "chin_raiser_bottom")
        p("CHIN_RAISER_TOP", "chin_raiser_top")
        p("DIMPLER_LEFT", "dimpler_left")
        p("DIMPLER_RIGHT", "dimpler_right")
        p("EYES_CLOSED_LEFT", "eyes_closed_left")
        p("EYES_CLOSED_RIGHT", "eyes_closed_right")
        p("EYES_LOOK_DOWN_LEFT", "eyes_look_down_left")
        p("EYES_LOOK_DOWN_RIGHT", "eyes_look_down_right")
        p("EYES_LOOK_LEFT_LEFT", "eyes_look_left_left")
        p("EYES_LOOK_LEFT_RIGHT", "eyes_look_left_right")
        p("EYES_LOOK_RIGHT_LEFT", "eyes_look_right_left")
        p("EYES_LOOK_RIGHT_RIGHT", "eyes_look_right_right")
        p("EYES_LOOK_UP_LEFT", "eyes_look_up_left")
        p("EYES_LOOK_UP_RIGHT", "eyes_look_up_right")
        p("INNER_BROW_RAISER_LEFT", "inner_brow_raiser_left")
        p("INNER_BROW_RAISER_RIGHT", "inner_brow_raiser_right")
        p("JAW_DROP", "jaw_drop")
        p("JAW_SIDEWAYS_LEFT", "jaw_sideways_left")
        p("JAW_SIDEWAYS_RIGHT", "jaw_sideways_right")
        p("JAW_THRUST", "jaw_thrust")
        p("LID_TIGHTENER_LEFT", "lid_tightener_left")
        p("LID_TIGHTENER_RIGHT", "lid_tightener_right")
        p("LIPS_TOWARD", "lips_toward")
        p("LIP_CORNER_DEPRESSOR_LEFT", "lip_corner_depressor_left")
        p("LIP_CORNER_DEPRESSOR_RIGHT", "lip_corner_depressor_right")
        p("LIP_CORNER_PULLER_LEFT", "lip_corner_puller_left")
        p("LIP_CORNER_PULLER_RIGHT", "lip_corner_puller_right")
        p("LIP_FUNNELER_LEFT_BOTTOM", "lip_funneler_left_bottom")
        p("LIP_FUNNELER_LEFT_TOP", "lip_funneler_left_top")
        p("LIP_FUNNELER_RIGHT_BOTTOM", "lip_funneler_right_bottom")
        p("LIP_FUNNELER_RIGHT_TOP", "lip_funneler_right_top")
        p("LIP_PRESSOR_LEFT", "lip_pressor_left")
        p("LIP_PRESSOR_RIGHT", "lip_pressor_right")
        p("LIP_PUCKER_LEFT", "lip_pucker_left")
        p("LIP_PUCKER_RIGHT", "lip_pucker_right")
        p("LIP_STRETCHER_LEFT", "lip_stretcher_left")
        p("LIP_STRETCHER_RIGHT", "lip_stretcher_right")
        p("LIP_SUCK_LEFT_BOTTOM", "lip_suck_left_bottom")
        p("LIP_SUCK_LEFT_TOP", "lip_suck_left_top")
        p("LIP_SUCK_RIGHT_BOTTOM", "lip_suck_right_bottom")
        p("LIP_SUCK_RIGHT_TOP", "lip_suck_right_top")
        p("LIP_TIGHTENER_LEFT", "lip_tightener_left")
        p("LIP_TIGHTENER_RIGHT", "lip_tightener_right")
        p("LOWER_LIP_DEPRESSOR_LEFT", "lower_lip_depressor_left")
        p("LOWER_LIP_DEPRESSOR_RIGHT", "lower_lip_depressor_right")
        p("MOUTH_LEFT", "mouth_left")
        p("MOUTH_RIGHT", "mouth_right")
        p("NOSE_WRINKLER_LEFT", "nose_wrinkler_left")
        p("NOSE_WRINKLER_RIGHT", "nose_wrinkler_right")
        p("OUTER_BROW_RAISER_LEFT", "outer_brow_raiser_left")
        p("OUTER_BROW_RAISER_RIGHT", "outer_brow_raiser_right")
        p("TONGUE_DOWN", "tongue_down")
        p("TONGUE_LEFT", "tongue_left")
        p("TONGUE_OUT", "tongue_out")
        p("TONGUE_RIGHT", "tongue_right")
        p("TONGUE_UP", "tongue_up")
        p("UPPER_LID_RAISER_LEFT", "upper_lid_raiser_left")
        p("UPPER_LID_RAISER_RIGHT", "upper_lid_raiser_right")
        p("UPPER_LIP_RAISER_LEFT", "upper_lip_raiser_left")
        p("UPPER_LIP_RAISER_RIGHT", "upper_lip_raiser_right")
    }
}
