#!/usr/bin/env bash
# Deploy weftspun_studio and its CockroachDB host as Podman quadlets.
# RFD 0058. No systemd oneshot or hand-written .service units — every
# unit here is generated by podman-system-generator from a .container/
# .volume/.network/.build file under weftspun_studio/deploy/quadlet/.
#
# Usage: sudo bash scripts/deploy-weftspun-quadlet.sh
#
# Syncs this repo to /opt/weftspun/src (the build context the quadlet
# .build units point at — see weftspun.build and weftspun-crdb.build),
# installs the quadlet files, and lets systemd build and start both
# containers.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="/opt/weftspun/src"
QUADLET_DIR="/etc/containers/systemd"

if [[ $EUID -ne 0 ]]; then
  echo "run as root: sudo bash $0" >&2
  exit 1
fi

if ! command -v podman &>/dev/null; then
  echo "podman not found" >&2
  exit 1
fi

cgroups_version="$(podman info --format '{{.Host.CgroupsVersion}}')"
if [[ "$cgroups_version" != "v2" ]]; then
  echo "quadlet needs cgroups v2, host reports $cgroups_version" >&2
  exit 1
fi

# --- sync source ------------------------------------------------------
# The .build quadlets read the Dockerfile from a fixed path, so the
# repo has to live somewhere stable regardless of where it was cloned
# for development.

mkdir -p "$SRC_DIR"
rsync -a --delete \
  --exclude '_build' --exclude 'deps' --exclude '.git' \
  --exclude 'burrito_out' --exclude 'node_modules' \
  "$ROOT/" "$SRC_DIR/"
echo "synced $ROOT -> $SRC_DIR"

# --- quadlet units ------------------------------------------------------

mkdir -p "$QUADLET_DIR"
install -m 0644 "$ROOT"/weftspun_studio/deploy/quadlet/*.network "$QUADLET_DIR/"
install -m 0644 "$ROOT"/weftspun_studio/deploy/quadlet/*.volume "$QUADLET_DIR/"
install -m 0644 "$ROOT"/weftspun_studio/deploy/quadlet/*.build "$QUADLET_DIR/"
install -m 0644 "$ROOT"/weftspun_studio/deploy/quadlet/*.container "$QUADLET_DIR/"

systemctl daemon-reload

# Quadlet honors each unit's own [Install] section at generation time
# — `systemctl enable` is for a hand-written unit's symlinks, and
# refuses on a generated one ("transient or generated"). `start` is
# the right verb here; the WantedBy= lines already wired the boot-time
# enablement when daemon-reload ran the generator.
#
# weftspun.service pulls in weftspun-crdb.service via Requires=/After=,
# and both pull in their .build/.volume/.network units automatically,
# so starting weftspun.service alone brings the whole stack up. The
# first start builds both images, which is slower than a normal
# systemd start — TimeoutStartSec=120 in weftspun.container covers it.
systemctl start weftspun.service

echo "=== weftspun.service ==="
systemctl --no-pager status weftspun.service || true
echo "=== weftspun-crdb.service ==="
systemctl --no-pager status weftspun-crdb.service || true
