name: GDExtension Build

on:
  workflow_call:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        os: ["macos-latest", "windows-2022"]

    steps:
      - name: Checkout source
        #v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Python
        #v6.2.0
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.x'

      - name: Install SCons
        run: pip install scons jinja2 pyside6

      - name: Restore openUSD cache
        #v5.0.4
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            thirdparty/openusd-26.05*
          key: ${{ matrix.os }}-openusd-v26.05

      - name: Build GDExtension
        working-directory: .
        # we always need to build debug & release targets
        run: |
          scons target=template_debug
          scons target=template_release
        shell: bash

      - name: Save openUSD to cache
        #v5.0.4
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            thirdparty/openusd-26.05*
          key: ${{ matrix.os }}-openusd-v26.05

      - name: Prepare artifacts
        working-directory: .
        run: |
          mkdir -p artifacts/gdextension
          mkdir -p artifacts/sdk
          cp -r addon/IDTXFlow artifacts/gdextension/
          cp -r build/idtxflow-sdk artifacts/sdk/
        shell: bash

      - name: Zip binaries and SDK (macOS)
        if: runner.os == 'macOS'
        working-directory: .
        shell: bash
        run: |
          zip -r gdextension-${{ runner.os }}.zip artifacts/gdextension
          zip -r idtxflow-sdk-${{ runner.os }}.zip artifacts/sdk

      - name: Zip binaries and SDK (Windows)
        if: runner.os == 'Windows'
        working-directory: .
        shell: pwsh
        run: |
          Compress-Archive -Path artifacts\gdextension\* -DestinationPath gdextension-${{ runner.os }}.zip
          Compress-Archive -Path artifacts\sdk\* -DestinationPath idtxflow-sdk-${{ runner.os }}.zip

      - name: Upload artifact
        #v7.0.0
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: gdextension-${{ runner.os }}
          path: |
            ./gdextension-${{ runner.os }}.zip
            ./idtxflow-sdk-${{ runner.os }}.zip
